### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by Po-Ting-lin** [Darkoon/CudaOtsu#11]
Hi, 

Thanks for sharing this!
Is there any comparison about performance between this implementation and the otsu in opencv (cpu version)?

Lin

**Comment by palucdev** [comment]
Hey, sorry for late response and thanks for stopping by :) 

I decided to follow own implementations and comparison between them just for a sake of simiplicity when it comes to run configurations. If there are reasonable close configuration options for my app and any other app/library that does otsu, I think that it can be compared.

If you (or anyone reading this :)) have a suggestion on how I can add some more configuration options, please post me a github issue with description.
